### ISSUE TITLE
4_PE_ProcessExtension_Material needs final revision

### ISSUE THREAD

**Issue by CarrerF** [IndEcol/RECC-ODYM#52]
Just a reminder that 4_PE_ProcessExtension_Material needs final revision on some materials.

In the environmental extension update, impact contributions (both direct and indirect) from 4_EI_ProcessEnergyIntensity are subtracted from 4_PE_ProcessExtension_Material to get the process Residuals. 

Energy contributions come from literature, impact factors from Ecoinvent/OpenLCA. Currently, some residuals are negative. To ensure non-negative values, I think different products in OpenLCA should be chosen as they should match the production system described in the reference literature.

**Comment by stefanpauliuk** [comment]
Thanks for the reminder @CarrerF , I checked the residual for material production impacts in the RECC model and the two materials that don't have a positive residual are steel/iron and paper.
That is not a surprise, given that the ecoinvent LCI for steel/iron contains about 25% scrap input and the energy input for paper production comes mostly from on-site combustion of wood residues and not from natural gas.

I created an update on the materials workbook to fix (scale up ecoinvent LCI for steel and use ecoinvent el. and nat. gas for paper), see
\Dropbox\RECC_v2_5_v2_6\data\RECC_v2_5_raw_data_archive\energy_supply_materials_production\Material_workbook\RECC_Materials_Workbook_v4.xlsx

I also shifted from land occupation (that contains some very aggregate and coarse biodiversity impact weighting) to total land use, where all occupied land is just added up, like for the material footprint.

From these updated data, all RECC intermediate and final results are plausible and positive.
Will send an update via the email later.

**Comment by stefanpauliuk** [comment]
Another update on the environmental extensions.

Here, the calculation scheme with the new parameters is shown, and another check was made.
![Extensions_v1](https://github.com/IndEcol/RECC-ODYM/assets/8901377/abf3e040-6fd2-42e5-923e-f00ecdb7371c)

The RECC model now also calculates and exports primary energy as well as a number of materal footprint indicators.

'primary energy' was added as an env. extension.

The fossil fuel use and biomass use of energy supply is now included in the material footprint.

Therefore, new data were added to the following parameters and documented with data processes:
All changes uploaded to \Dropbox\RECC_v2_5_v2_6\data\CURRENT_V2_5\

3_EI_SpecificEnergy_EnergyCarriers_V1.0: 
was renamed from 4_EI_Specific.... because it relates to products (3_...) and not processes (4_...)
The energy content of fuel wood was added.

4_PE_ProcessExtensions_Industry_V1.1:
Added data for fossil fuel and biomass RMI as well as primary energy intensity for electricity generation.

4_PE_ProcessExtensions_EnergyCarriers_V1.2:
Added data for fossil fuel and biomass RMI as well as primary energy intensity for the energy carriers other than electricity.
