### ISSUE TITLE
Integrate scenario target table interpolation into the RECC model

### ISSUE THREAD

**Issue by stefanpauliuk** [IndEcol/RECC-ODYM#53]
@CarrerF suggested to generate the interpolations of the scenario target table on the fly, and turing @TomerFishman 's interpolation script into an ODYM function. This would reduce the parameter count by about 30 and would make the database more compact, plus that it would save a lot of time that is spent for copying these interpolated data to the RECC database.

@stefanpauliuk added that next to implementing this automated target table interpolation, also the interpolation of other parameters should be automized and auto-executed by setting appropriate control flags in the config file, calling a general interpolation function, and not by hand-coded interpolations in the main model script.

**Comment by CarrerF** [comment]
![image](https://github.com/IndEcol/RECC-ODYM/assets/98351491/23b7f46d-e752-4755-9065-991f8545f000)

**Comment by CarrerF** [comment]
I have not fully understood the translation of target tables into canvas.

After our last conversation, I had the impression that this was the optimal set-up for target-based parameters:
![image](https://github.com/IndEcol/RECC-ODYM/assets/98351491/8f8cd178-a72e-42a3-b15b-e281b171b720)

The target-tables excel is discarded and each dataset is already in the database, with only current and target values.  The interpolation method eventually allows for intermediate values.

Would you consider something different?

**Comment by chauenstein** [comment]
This looks very nice @CarrerF Thanks!
Is it possible to choose the values for 't' flexibly? E.g., give a target value for the year 2040, which remains constant thereafter?
Additionally, it would be great to have the possibility of using intermediate steps (e.g., if I want to provide annual values for the start of the period, in order to calibrate the model to the historic development (e.g. 2016-2020)). Is that already possible?

**Comment by CarrerF** [comment]
"If the element has an empty space in the classification, so it will when called"
It's the case of elements like "concrete aggregates", with a space in them. It does not relate to the aspects that we are replicating right now, because scenarios LED, SSP1 and SSP2 are 1-world only, but I made the code flexible for future use.
If, for example, one would like to replicate the values of cement for concrete aggregates in a certain parameter, the notation would be replicate_m_concrete aggregates_with_cement, keeping the space.

"could you please transfer these values for the 1_F and 2_S"
ok!

"The typical table also has one column aspect (S), but for the general case, there can be any number of aspects, right?"
Yes, the number of aspects in the parameter is arbitrary, as well as the position of t/c in the Index Structure.
The data format list/table does not relate to the methods. Once ReadParameterXLSX has created the multi-dimensional array of Values, the methods replicate/interpolate/copy act on it, and look for the index position in the parameter's Index Structure.
This should cover any general case.
For example. the interpolation method is  currently used on many parameters with structures "GrtS" or variations ("stGr", "VrtS", "BrtS", "NrtS", "srtS", "prtS", "urtS", "GrtS"), "cmpr" (also "cmBr", "cmNr") or simply "c" (for 6_MIP_GWP_Bio).
But one could, for example, use the interpolation method for 3_SHA_EnergyCarrierSplit_Buildings, whose structure is "VRrnt". 
An example of a 2-rows and 2-columns table is 2_P_RECC_Population_SSP_32R_V2.2. If for a country you had only historic data and a future projection, then 'interpolate_t_2023_2060_linear' would work. Eventually, it could also be combined: ['interpolate_t_2023_2060_linear',replicate_S_LED_with_SSP2'].

**Comment by stefanpauliuk** [comment]
Interpolation controlled by config file is now routinely working, great advancement!
