### ISSUE TITLE
'Material footprint, fossil fuels, for the entire (system-wide) energy supply' results for r>1 off?

### ISSUE THREAD

**Issue by chauenstein** [IndEcol/RECC-ODYM#62]
@stefanpauliuk 
When I run the model (RECC-ODYM commit 7721b7d) with more than one region, I get a somewhat puzzling result for 'Material footprint, fossil fuels, for the entire (system-wide) energy supply'. To my understanding, this should be a part of, or at most equal to 'Material footprint, fossil fuels, system-wide _3579di'. However, it is substantially larger than 'Material footprint, fossil fuels, system-wide _3579di'. 
(In case of a model run with only one region, this is not the case. Running the model for two regions individually and summing up the results for 'Material footprint, fossil fuels, for the entire (system-wide) energy supply' of these two model runs gives a substantially smaller result, than the result for 'Material footprint, fossil fuels, for the entire (system-wide) energy supply' in a single model run with both regions calculated simultaneously.)

**Comment by stefanpauliuk** [comment]
**Some background:** Currently: impact of energy carriers other than electricity (goal, gas, diesel ...) are constant over time and space. Electricity impacts per MJ are region- and time-dependent. For the use phase, the el. mix of the region where the stock is located is taken. For material production, manufacturing, and recycling (PMR): For one region selected, the el. mix of that region is taken for PMR. For multiple regions, the global average el. mix is taken instead, representing global average supply chain impacts! (RECC main script around L2600, section ' # J) Calculate emissions from energy supply')

**These two add up:**
Material footprint, metal ores, system-wide _3579di == Material footprint, metal ores, for primary material production
Material footprint, non-metallic minerals, system-wide _3579di == Material footprint, non-metallic minerals, for primary material production
**These two don't add up:**
Material footprint, biomass (dry weight), system-wide _3579di (with components for biomass)
Material footprint, fossil fuels, system-wide _3579di (with components for fossil fuels)

The reason is that the _3579di aggregate is calculated differently than the detailed breakdown:

aggregate:
Impacts_System_3579di consists of SysExt_Impacts_UsePhase_7d + SysExt_Impacts_OtherThanUsePhaseDirect + SysExt_Impacts_EnergyRecoveryWaste_9di + np.einsum('xtrm->xt',SysExt_CO2UptakeImpacts_Forests)

detailed:
Impacts_Energy_Supply_All[FosFuel_loc,:,:,:], taken from SysExt_IndirectImpacts_EnergySupply_All[:,:] # For checking the material footprint, energy impacts on GWP are accounted for elsewhere. Emissions from energy use are NOT included here (combustion emissions).
Calculated from SysVar_TotalEnergyDemand, which includes reductions of energy supply through the use of internal wood waste as wood fuel (wood fuel substitution) and the supply of internal electricity from the combustion of wood waste.

Hence, we need to consistently account for reductions of energy supply through the use of internal wood waste as wood fuel (wood fuel substitution) and the supply of internal electricity from the combustion of wood waste. Will look into that now.

**Comment by stefanpauliuk** [comment]
Also, there is some intended double-counting:
(a) Material footprint, fossil fuels, for primary material production (both energy supply and feedstock)
(b) Material footprint, fossil fuels, for the entire (system-wide) energy supply
(a) shows the impact of primary material production, including its energy supply, hence part of (b)! 
See the Impacts_System_3579di indicator for a consistent number for the entire system.

Same for biomass:
(a) Material footprint, biomass, for primary material production (both energy supply and feedstock)
(b) Material footprint, biomass/biofuel, for the entire (system-wide) energy supply

**Comment by stefanpauliuk** [comment]
So for fossil fuels, things are working as intended. For biomass, the sum of the individual flows should also be larger than the _3579di total, but isn't. This I still need to check (is the internally substituted fuel wood removed from the footprint?)

**Comment by stefanpauliuk** [comment]
Material footprints now add up to the total for the four categories.
