### ISSUE TITLE
Negative values in Population interpolations for SSP scenarios IIASA

### ISSUE THREAD

**Issue by Johanvelezh** [IndEcol/RECC-ODYM#65]
Hi @stefanpauliuk @chauenstein  In the population dataset "SSP_PopData", an interpolation of the SSP scenarios from IIASA is conducted for all the world countries. Some countries for different years and scenarios have negative values. For example ABW country code for the years 2011 to 2014 IIASA GDP scenario, COK country code 2010-2016 IIASA GDP scenario.

It would make sense to check the interpolation Python file "SSPDataParse"

**Comment by stefanpauliuk** [comment]
Hi @Johanvelezh which parameter (name, version) are you referring to? 
The main RECC population paramter 2_P_RECC_Population_SSP_32R_V2.2 does not contain any negative values.

**Comment by chauenstein** [comment]
Hi @Johanvelezh, thanks for pointing this out. This happens when a country is not included in the model that is used to provide the population simulations (e.g., ABW in the model IIASA GDP) and thus the interpolation uses a target value of zero. Then the spline interpolation also yields negative values. As this is only the case for few countries, I would not worry to much about it, except when explicitly data for this country is required. Then, the other models could be checked, if they include population growth assumptions for the required country.

**Comment by Johanvelezh** [comment]
Hi @chauenstein thank you for the prompt response. I  understand. Make sense for me not to worry about the countries with negative values as they are few and are not included in my model.
I will close this issue.
